# Form implementation generated from reading ui file 'C:\Users\HP\PycharmProjects\BAI TAP KTLT\EX22\baitap22.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(656, 544)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 50, 421, 51))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(40, 110, 561, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 301, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 331, 31))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 331, 31))
        self.label_4.setObjectName("label_4")
        self.lineEditN = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditN.setGeometry(QtCore.QRect(320, 41, 171, 31))
        self.lineEditN.setObjectName("lineEditN")
        self.lineEditD = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditD.setGeometry(QtCore.QRect(360, 80, 171, 31))
        self.lineEditD.setObjectName("lineEditD")
        self.lineEditM = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditM.setGeometry(QtCore.QRect(350, 120, 171, 31))
        self.lineEditM.setObjectName("lineEditM")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(250, 300, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:\\Users\\HP\\PycharmProjects\\BAI TAP KTLT\\EX22\\images/8468578_calculator_finance_calculate_mathematics_calculation_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(40, 360, 561, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(30, 40, 211, 41))
        self.label_5.setObjectName("label_5")
        self.lineEditProfit = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.lineEditProfit.setGeometry(QtCore.QRect(260, 40, 231, 41))
        self.lineEditProfit.setObjectName("lineEditProfit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 656, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#ff0000;\">Light Bulb Inspection Probability Calculator </span></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Input N,D,M:"))
        self.label_2.setText(_translate("MainWindow", "Total Number of Light Bulbs (N): "))
        self.label_3.setText(_translate("MainWindow", "Number of Damaged Light Bulbs (D):"))
        self.label_4.setText(_translate("MainWindow", "Number of Light Bulbs to Check (M):"))
        self.pushButton.setText(_translate("MainWindow", "Calculate"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Result:"))
        self.label_5.setText(_translate("MainWindow", "Calculated Probability:"))
